### PR TITLE
I0673 miovision find_gaps fixes

### LINKED ISSUE #419: Miovision Gap Finding SQL function doesn't correctly identify entire missing days
Not only does it not alert us to these, but it does also fill in 0s for them instead of `NULL`

### LINKED ISSUE #673: miovision_api.find_gaps improvements
Looking at the pull_miovision airflow logs, this step alone takes 40 minutes to run. 

- Explain shows it includes multiple seq scans over `miovision_api.volumes` table
- 10+ CTEs
- long and not well commented
- use of `ful` table probably not necessary.
- needs fluffing for readability 
- Fails silently for intersections with no data at all
- For gaps overlapping multiple hours, only the start of the hour is used to determine the allowed_gap threshold.
- Holidays not considered when determining weekdays/weekends
- gap sizes are exaggerated by 1 minute, since both gap_start and gap_end are exclusive. 

@scann0n's gap and islands approach for rescu can be used for inspiration (runs in just a few seconds for whole year of rescu data): https://github.com/CityofToronto/bdit_data-sources/blob/d85291a5b76b65cc6348f5d30949a1887b35e236/volumes/rescu/date_evaluation/x2_rescu_gaps.sql

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:
- Completely rewrote miovision `find_gaps` function to fix many issues described in #673 including:
- Speed (<1 min from 40 mins), readability improvements
- Catch gaps for detectors that ~~reported no data or~~ had an outage starting midday by performing a cross join of intersections and start/end of day
- ~~Removed second date parameter, since based on a 60 day lookback it should be running one date at a time. Made necessary changes to run_api to support this change.~~ Used window function to correctly reference a rolling lookback when run for multiple days rather than use a single fixed lookback. See: https://github.com/CityofToronto/bdit_data-sources/pull/678#issuecomment-1858066978
- Considered `ref.holidays` when determining weekday/weekend.
- Fixed a minor bug where gap sizes are exaggerated by 1 minute since the gap_start was incorrectly treated as inclusive. 
- ~~Fixed a bug where gaps sometimes ended on the hour, causing the whole following hour to be excluded.~~ Cross join gaps to the 15 minute periods they overlap with, which fixes some incorrect edge cases in gap expansion to hour periods. 
  - Adjust the join when aggregating into `volumes_15min_mvt` to reflect this change. 
- ~~Changed gaps to more explicitly reference the beginning and end of the hour instead of the gap start and end since, the gap list was not complete anyway (due to DISTINCT ON) and could cause confusion if used for other purposes.~~
- Updated readme to reflect changes to `find_gaps`.

**Latest update (2023-12-13):**
- Separate `gapsize_lookup` (previously a CTE) into a table so that it can also be used downstream by new `daily_volumes` table (#780).
- In `gapsize_lookup`, include both total volumes to be used for gap threshold determination, and individual classification volumes to be used for imputing the missing volume from gaps. 

## Issue(s) this solves:
- Closes #673 
- Closes #419 

## What, in particular, needs to reviewed:
- volumes/miovision/sql/function-find_gaps.sql: completely rewrote find_gaps
- volumes/miovision/api/intersection_tmc.py: Changes to reflect removal of end_date from find_gaps. 

## What needs to be done by a sysadmin after this PR is merged
See https://github.com/CityofToronto/bdit_data-sources/pull/678#issuecomment-1892761571 for implementation steps.

### CODE REVIEW

**Comment by radumas** [comment]
> Changed gaps to more explicitly reference the beginning and end of the hour instead of the gap start and end since, the gap list was not complete anyway (due to DISTINCT ON) and could cause confusion if used for other purposes.

The point about a confusion concern is a good one. I do wonder if we should be storing both the hourly resolution and minute resolution gap data. The minute resolution could help with debugging, or for comparing to the alert data when it comes in.

**Comment by gabrielwol** [comment]
> > Changed gaps to more explicitly reference the beginning and end of the hour instead of the gap start and end since, the gap list was not complete anyway (due to DISTINCT ON) and could cause confusion if used for other purposes.
> 
> The point about a confusion concern is a good one. I do wonder if we should be storing both the hourly resolution and minute resolution gap data. The minute resolution could help with debugging, or for comparing to the alert data when it comes in.

I thought about this while writing this PR. The current summary is a bit high level for some purposes. 
We could create a new table using this [intermediate CTE](https://github.com/CityofToronto/bdit_data-sources/pull/678/files#diff-ce48f0734a54414a1084a90fa5e9c509ce7e0b0d36af7517d5ab4d16969337dfR107-R124) and then `unacceptable_gaps` table (hourly summary) would become a view on top of that.

**Comment by gabrielwol** [comment]
Here are some sample rows from the new update to help with review: 

An intersection with some small gaps: 
| "intersection_uid" | "gap_start"           | "gap_end"             | "gap_minutes_total" | "allowable_total_gap_threshold" | "datetime_bin"        | "gap_minutes_15min" | "avg_historical_total_vol" | "avg_historical_veh_vol" |
|--------------------|-----------------------|-----------------------|---------------------|---------------------------------|-----------------------|---------------------|----------------------------|--------------------------|
| 12                 | "2023-11-01 08:42:00" | "2023-11-01 08:47:00" | 5                   | 5                               | "2023-11-01 08:30:00" | 3                   | 195                        | 82                       |
| 12                 | "2023-11-01 08:42:00" | "2023-11-01 08:47:00" | 5                   | 5                               | "2023-11-01 08:45:00" | 2                   | 130                        | 55                       |
| 12                 | "2023-11-01 17:54:00" | "2023-11-01 17:59:00" | 5                   | 5                               | "2023-11-01 17:45:00" | 5                   | 511                        | 129                      |
| 12                 | "2023-11-01 18:18:00" | "2023-11-01 18:23:00" | 5                   | 5                               | "2023-11-01 18:15:00" | 5                   | 492                        | 137                      |

An intersection that is not present at all (first 10 rows): 
| "intersection_uid" | "gap_start"           | "gap_end"             | "gap_minutes_total" | "allowable_total_gap_threshold" | "datetime_bin"        | "gap_minutes_15min" | "avg_historical_total_vol" | "avg_historical_veh_vol" |
|--------------------|-----------------------|-----------------------|---------------------|---------------------------------|-----------------------|---------------------|----------------------------|--------------------------|
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 10                              | "2023-11-01 00:00:00" | 15                  | 140                        | 134                      |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 10                              | "2023-11-01 00:15:00" | 15                  | 140                        | 134                      |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 10                              | "2023-11-01 00:30:00" | 15                  | 140                        | 134                      |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 10                              | "2023-11-01 00:45:00" | 15                  | 140                        | 134                      |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 01:00:00" | 15                  | 79                         | 74                       |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 01:15:00" | 15                  | 79                         | 74                       |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 01:30:00" | 15                  | 79                         | 74                       |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 01:45:00" | 15                  | 79                         | 74                       |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 02:00:00" | 15                  | 59                         | 56                       |
| 63                 | "2023-10-31 23:45:00" | "2023-11-02 00:00:00" | 1455                | 15                              | "2023-11-01 02:15:00" | 15                  | 59                         | 56                       |

**Comment by gabrielwol** [comment]
Note to self: readme updates are now outdated based on yesterdays changes.

**Review by radumas — COMMENTED** [review]
Some initial comments while I continue to work through the find gaps function

File: volumes/miovision/sql/function-find_gaps.sql [hunk 1]
```diff
@@ -1,116 +1,191 @@
...
-    mio.hourly_bin::time without time zone AS time_bin,
-    avg(mio.vol) AS avg_vol,
+--find only intersections active today
+WITH daily_intersections AS (
+    SELECT DISTINCT v.intersection_uid
+    FROM miovision_api.volumes AS v
+    INNER JOIN miovision_api.intersections AS i USING (intersection_uid)
+    WHERE
+        v.datetime_bin >= start_date
+        AND v.datetime_bin < start_date + interval '1 day'
```
[the remark this answers is not in the document]
Comment (gabrielwol) [reply volumes/miovision/sql/function-find_gaps.sql:25]: Correct, these will instead go in anomalous_ranges table with #777.
I updated that part of the PR description.

File: volumes/miovision/sql/function-find_gaps.sql [hunk 2]
```diff
@@ -1,116 +1,199 @@
...
+            interval '15 minutes'
+    ) AS bins(datetime_bin) ON
+        bins.datetime_bin >= datetime_bin(bt.gap_start, 15)
+        AND bins.datetime_bin < datetime_bin_ceil(bt.gap_end, 15)
+    --find the acceptable gap size based on historical lookback.
+	LEFT JOIN gapsize_lookup AS gl ON
+        gl.intersection_uid = bt.intersection_uid
+        AND gl.time_bin = date_part('hour', bins.datetime_bin)
+        AND gl.weekend = bt.weekend,
+	LATERAL (
```
Comment (radumas) [inline volumes/miovision/sql/function-find_gaps.sql:169]: Have you tested this? I'm noticing the comma before the LATERAL and wondering if that would bug...

File: volumes/miovision/sql/function-find_gaps.sql [hunk 3]
```diff
@@ -1,116 +1,199 @@
...
+        gl.gap_tolerance AS allowable_total_gap_threshold,
+        bins.datetime_bin,		
+        round(gm.gap_minutes_15min) AS gap_minutes_15min,
+        --avg historical volumes during the gaps to use for imputation
+        --or decision on summary data quality
+        round(gl.avg_vol * gm.gap_minutes_15min / 60) AS avg_historical_total_vol,
+        round(gl.avg_vehicle_vol * gm.gap_minutes_15min / 60) AS avg_historical_veh_vol
+	FROM bin_times AS bt
+    --match gaps to the 15 minute bins they intersect
+    LEFT JOIN generate_series(
```
Comment (radumas) [inline volumes/miovision/sql/function-find_gaps.sql:156]: I think these `LEFT JOIN`s end up effectively being an `INNER JOIN` given the `WHERE` clause depends on `gm` which depends on the two previous joins. Would be more explicit to make them `INNER`

File: volumes/miovision/sql/function-find_gaps.sql [hunk 4]
```diff
@@ -1,116 +1,199 @@
...
+                 LEAST(bt.gap_end, bins.datetime_bin + interval '15 minutes')
+                 - GREATEST(bt.gap_start, bins.datetime_bin)
+                ) / 60 AS gap_minutes_15min
+	) AS gm
+	WHERE
+		gm.gap_minutes_total >= gl.gap_tolerance
+		AND bt.bin_break = True
+		AND bt.gap_end IS NOT NULL
+        --exclude gaps that are entirely without of todays interval
+        AND NOT(bins.datetime_bin + gm.gap_minutes_15min * '1 minute'::interval) <= start_date
```
Comment (radumas) [inline volumes/miovision/sql/function-find_gaps.sql:183]: why not use `gap_end` here?

**Review by radumas — CHANGES_REQUESTED** [review]
Great work revamping this very complicated function. I'm excited for the performance improvements and the better information coming out of the process.

As far as I can tell the updated function is correct. I have some suggestions for documentation improvements from a previous review and I've left some comments on the joins which I think should be more explicit.

File: volumes/miovision/sql/function-find_gaps.sql (hunk 2 above)
Comment (gabrielwol) [reply volumes/miovision/sql/function-find_gaps.sql:169]: Not a bug :) https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL

File: volumes/miovision/sql/function-find_gaps.sql (hunk 4 above)
Comment (radumas) [reply volumes/miovision/sql/function-find_gaps.sql:183]: Ignore my previous comment. Don't you want to exclude `datetime_bin < start_date`?

File: volumes/miovision/sql/function-find_gaps.sql (hunk 2 above)
Comment (radumas) [reply volumes/miovision/sql/function-find_gaps.sql:169]: I think that's when using `LATERAL` in the `FROM` clause, but this would be the in the `JOIN` area... so I think you need `INNER JOIN LATERAL`

Comment (radumas) [reply volumes/miovision/sql/function-find_gaps.sql:169]: but if it works....

File: volumes/miovision/sql/function-find_gaps.sql (hunk 4 above)
Comment (gabrielwol) [reply volumes/miovision/sql/function-find_gaps.sql:183]: I had to think about this for a while. 
I think NOT(gap_end <= start_date) is actually correct. If it's a gap that overlaps the current day at all, we want to include the 23:45-00:00 datetime_bin as a gap, because it wouldn't be caught if only looking at yesterdays data.

**Comment by gabrielwol** [comment]
@radumas the sql is ready for re-review. I still need to do the readme. 
All of these objects are created and tested in `gwolofs` schema: 
```sql
--test for a holiday
SELECT gwolofs.gapsize_lookup_insert('2023-09-04');
SELECT * FROM gwolofs.gapsize_lookup WHERE dt = '2023-09-04'::date;
--and a non-holiday
SELECT gwolofs.gapsize_lookup_insert('2023-09-05');
SELECT * FROM gwolofs.gapsize_lookup WHERE dt = '2023-09-05'::date;

SELECT gwolofs.find_gaps('2023-09-05');
SELECT * FROM gwolofs.unacceptable_gaps WHERE dt = '2023-09-05'::date;

SELECT gwolofs.insert_volumes_daily('2023-09-05'::date, '2023-09-06'::date);
SELECT * FROM gwolofs.volumes_daily WHERE dt = '2023-09-05';
```

**Review by radumas — APPROVED** [review]
Great work. Love the innovative uses of `LATERAL`, `GROUPING SET`, and `PERFORM`!

**Comment by radumas** [comment]
I'll take care of the merging and post-merge actions tomorrow

**Comment by radumas** [comment]
As mentioned in offline discussions, this current process takes 40s/day, would probably take.... just over 16 hours to run the past 4 years of data? 

We've discussed using a `WINDOW` to have a rolling 60 day lookback and enabling batch processing more data at a time.

**Comment by gabrielwol** [comment]
@radumas Made some major changes yesterday to find_gaps to support running for multiple days at a time using window functions. 
Tested for a month and got the same results with massive speed improvements!
There was one row difference, but I narrowed it down to an edge case where two distinct gaps occur in the same 15 minute bin, and the `DISTINCT ON ... ORDER BY` was not specific enough and selected different gaps for the same bin on the two runs. Fixed now by adding to the ORDER BY clause. 

```sql
--test the new version, runs for a range. Uses window functions for speed.
SELECT * FROM gwolofs.find_gaps('2023-09-01', '2023-10-01')
--3:18, 91 rows
CREATE TABLE gwolofs.unacceptable_gaps_multiday_test AS SELECT * FROM gwolofs.unacceptable_gaps;

--test the old version, one day at a time using lateral
SELECT *
FROM generate_series('2023-09-01'::date, '2023-10-01'::date - interval '1 day', interval '1 day') AS dates(dt),
LATERAL (
    SELECT gwolofs.find_gaps(dt)    
) old
--46:14, 91 rows 

--there's one record different between the two tables: 
(TABLE gwolofs.unacceptable_gaps_multiday_test EXCEPT TABLE gwolofs.unacceptable_gaps)
UNION ALL
(TABLE gwolofs.unacceptable_gaps EXCEPT TABLE gwolofs.unacceptable_gaps_multiday_test) ;
```

**Comment by gabrielwol** [comment]
@chmnata Here's my plan for implementation. The new aggregations have already been staged in gwolofs schema. Most of this should be very fast to run because we can just swap out one partition for another without worrying about adding/dropping dependencies on the parent table. 

```sql
--check row counts for staging vs existing (volumes_15min)
--add any new values with: SELECT gwolofs.aggregate_15_min(start_date::date, start_date::date)
--new counts should generally be a bit higher because only 15 minute bins around each gap are removed rather than full hour. 
SELECT * FROM 
(SELECT date_part('year', datetime_bin), COUNT(*) AS staging_count FROM gwolofs.volumes_15min GROUP BY 1) AS a
JOIN (
SELECT date_part('year', datetime_bin), COUNT(*) AS old_count FROM miovision_api.volumes_15min GROUP BY 1
) AS b USING (date_part)

/*
| date_part | staging_count | old_count | New/Old |
|-----------|---------------|-----------|---------|
| 2019      | 40570149      | 36085029  | 112.43% |
| 2020      | 44952832      | 40051723  | 112.24% |
| 2021      | 72398451      | 68843360  | 105.16% |
| 2022      | 76040372      | 75769512  | 100.36% |
| 2023      | 76483917      | 76468685  | 100.02% |
| 2024      | 2796476       | 2796476   | 100.00% |
*/

--check row counts for staging vs existing (volumes_15min_mvt) 
--add any new values with: SELECT gwolofs.aggregate_15_min_mvt(start_date::date, start_date::date)
--new counts should generally be a bit higher because only 15 minute bins around each gap are removed rather than full hour. 
SELECT * FROM 
(SELECT date_part('year', datetime_bin), COUNT(*) FROM gwolofs.volumes_15min_mvt GROUP BY 1) AS a
JOIN (
SELECT date_part('year', datetime_bin), COUNT(*) FROM miovision_api.volumes_15min_mvt GROUP BY 1
) AS b USING (date_part)

/*
| date_part | staging_count | old_count | New/Old |
|-----------|---------------|-----------|---------|
| 2019      | 50327545      | 45842425  | 109.78% |
| 2020      | 55680226      | 50788052  | 109.63% |
| 2021      | 89029997      | 85477585  | 104.16% |
| 2022      | 93711121      | 93291460  | 100.45% |
| 2023      | 94063199      | 94048474  | 100.02% |
| 2024      | 3495378       | 3486121   | 100.27% |
*/

--this table has no dependents.
--It should have foreign keys but they are currently missing from the database. Will create down below. 
DROP TABLE miovision_api.volumes_mvt_atr_xover;
ALTER TABLE gwolofs.volumes_mvt_atr_xover SET SCHEMA miovision_api;
ALTER TABLE miovision_api.volumes_mvt_atr_xover OWNER TO miovision_admins;

--drop/add volumes_15min partitions x (2019-2024)
DO $do$
DECLARE
	yyyy INTEGER;
    base_table TEXT;
    year_table TEXT;
BEGIN
	FOR yyyy IN 2019..2024 LOOP
        base_table := 'volumes_15min';
        year_table := base_table || '_'||yyyy::text;

        EXECUTE FORMAT $$
            DROP TABLE miovision_api.%I; --drop existing partition 
            ALTER TABLE gwolofs.%I DETACH PARTITION %I;
            ALTER TABLE miovision_api.%I ATTACH PARTITION gwolofs.%I
                FOR VALUES FROM (make_date(%L, 1, 1)::timestamp) TO (make_date(%L, 1, 1)::timestamp);
            ALTER TABLE gwolofs.%I SET SCHEMA miovision_api; 
            ALTER TABLE gwolofs.%I OWNER TO miovision_admins;
        $$, year_table, base_table, year_table, base_table, year_table, yyyy, yyyy+1, year_table, year_table;
	END LOOP;
END;
$do$ LANGUAGE plpgsql

--drop/add volumes_15min_mvt partitions x (2019-2024)
DO $do$
DECLARE
	yyyy INTEGER;
    base_table TEXT;
    year_table TEXT;
BEGIN
	FOR yyyy IN 2019..2024 LOOP
        base_table := 'volumes_15min_mvt';
        year_table := base_table || '_'||yyyy::text;

        EXECUTE FORMAT $$
            DROP TABLE miovision_api.%I; --drop existing partition 
            ALTER TABLE gwolofs.%I DETACH PARTITION %I;
            ALTER TABLE miovision_api.%I ATTACH PARTITION gwolofs.%I
                FOR VALUES FROM (make_date(%L, 1, 1)::timestamp) TO (make_date(%L, 1, 1)::timestamp);
            ALTER TABLE gwolofs.%I SET SCHEMA miovision_api;
            ALTER TABLE gwolofs.%I OWNER TO miovision_admins;
        $$, year_table, base_table, year_table, base_table, year_table, yyyy, yyyy+1, year_table, year_table;
	END LOOP;
END;
$do$ LANGUAGE plpgsql


--recreate foreign keys on volumes_mvt_atr_xover
--NOTE (These two are currently missing in the database but in github)
ALTER TABLE miovision_api.volumes_mvt_atr_xover
ADD CONSTRAINT atr_mvt_uid_volume_15min_mvt_uid_fkey FOREIGN KEY (volume_15min_mvt_uid)
    REFERENCES miovision_api.volumes_15min_mvt (volume_15min_mvt_uid) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE CASCADE;

ALTER TABLE miovision_api.volumes_mvt_atr_xover
ADD CONSTRAINT atr_mvt_uid_volume_15min_uid_fkey FOREIGN KEY (volume_15min_uid)
    REFERENCES miovision_api.volumes_15min (volume_15min_uid) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE CASCADE;

--update fkey references in miovision_api.volumes
--run this one year at a time by updating "FROM". May be very slow.
UPDATE miovision_api.volumes AS v
SET volume_15min_mvt_uid = v15.volume_15min_mvt_uid
FROM miovision_api.volumes_15min_mvt_2019 AS v15
WHERE
    v15.volume > 0
    AND v.intersection_uid = v15.intersection_uid
    AND v.datetime_bin >= v15.datetime_bin
    AND v.datetime_bin < v15.datetime_bin + interval '15 minutes'
    AND v.classification_uid = v15.classification_uid
    AND v.leg = v15.leg
    AND v.movement_uid = v15.movement_uid;

--this one is small and has no dependents.
DROP TABLE miovision_api.unacceptable_gaps;
ALTER TABLE gwolofs.unacceptable_gaps SET SCHEMA miovision_api;
ALTER TABLE miovision_api.unacceptable_gaps OWNER TO miovision_admins;

--a new table 
ALTER TABLE gwolofs.gapsize_lookup SET SCHEMA miovision_api;
ALTER TABLE miovision_api.gapsize_lookup OWNER TO miovision_admins;

--1 new function:
--CREATE: volumes/miovision/sql/function/function-gapsize_lookup_insert.sql

--3 modified functions (one with new param types):
DROP FUNCTION miovision_api.find_gaps(date, date); --replaced with (timestamp, timestamp)
--CREATE: volumes/miovision/sql/function/function-find_gaps.sql
--CREATE: volumes/miovision/sql/function/function-aggregate-volumes_15min_mvt.sql
--CREATE: volumes/miovision/sql/function/function-aggregate-volumes_15min_mvt_single_intersection.sql
```

**Comment by chmnata** [comment]
Can we detach and possibly move it to a temp schema before dropping the miovision tables? Kinda terrifying to drop as the first step :cat_yell:

**Comment by chmnata** [comment]
```
DO $do$
DECLARE
	yyyy INTEGER;
    base_table TEXT;
    year_table TEXT;
BEGIN
	FOR yyyy IN 2020..2024 LOOP
        base_table := 'volumes_15min';
        year_table := base_table || '_'||yyyy::text;

        EXECUTE FORMAT ($$
			ALTER TABLE miovision_api.%I DETACH PARTITION miovision_api.%I; -- base_table, year_table
			ALTER TABLE miovision_api.%I SET SCHEMA natalie; --year_table
            ALTER TABLE gwolofs.%I DETACH PARTITION gwolofs.%I; -- base_table, year_table
            ALTER TABLE miovision_api.%I ATTACH PARTITION gwolofs.%I 
                FOR VALUES FROM (make_date(%L, 1, 1)::timestamp) TO (make_date(%L, 1, 1)::timestamp);
            ALTER TABLE gwolofs.%I SET SCHEMA miovision_api; 
            ALTER TABLE miovision_api.%I OWNER TO miovision_admins;
        $$, base_table, year_table, 
			year_table, 
			base_table, year_table, 
			base_table, year_table, 
			yyyy, yyyy+1, 
			year_table, year_table);
	END LOOP;
END;
$do$ LANGUAGE plpgsql
```
Added drop pkey constraint here
```
DO $do$
DECLARE
	yyyy INTEGER;
    base_table TEXT;
    year_table TEXT;
	pkey TEXT;
BEGIN
	FOR yyyy IN 2020..2024 LOOP
        base_table := 'volumes_15min_mvt';
        year_table := base_table || '_'||yyyy::text;
		pkey := year_table ||'_pkey'; 
		
        EXECUTE FORMAT ($$
			ALTER TABLE miovision_api.%I DETACH PARTITION miovision_api.%I; -- base_table, year_table
			ALTER TABLE miovision_api.%I SET SCHEMA natalie; --year_table
            ALTER TABLE gwolofs.%I DETACH PARTITION gwolofs.%I; -- base_table, year_table
			ALTER TABLE gwolofs.%I DROP CONSTRAINT %I; -- year_table, pkey
            ALTER TABLE miovision_api.%I ATTACH PARTITION gwolofs.%I
                FOR VALUES FROM (make_date(%L, 1, 1)::timestamp) TO (make_date(%L, 1, 1)::timestamp);
            ALTER TABLE gwolofs.%I SET SCHEMA miovision_api;
            ALTER TABLE miovision_api.%I OWNER TO miovision_admins;
        $$, base_table, year_table,
			year_table,
			base_table, year_table,
			year_table, pkey,
			base_table, year_table,
			yyyy, yyyy+1,
			year_table, year_table);
	END LOOP;
END;
$do$ LANGUAGE plpgsql
```

**Comment by chmnata** [comment]
Both volume_15min and volume_15min_mvt are updated in the miovision_api schema. Currently testing the duration it will take to update volumes's mvt_uid. One day of updating took about 30 secs with some extremely explicit clauses. 
Half a month took ................. 47 mins and counting so this is gonna be looping day by day job. 

 How important is `volume_15min_mvt_uid` ? 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔

**Comment by chmnata** [comment]
- ✔️ All miovision agg table has been transferred from gwolofs to miovision_api. 
- ✔️Volumes table's volume_15min_mvt_uid has been updated. 
- ✔️find gaps functions and other agg table functions have been recreated 
- A check on volume_15min_mvt_uid = volume_15min_mvt_uid  on `miovision_api.volumes_202401` and ` miovision_api.volumes_15min_mvt_2024` shows that there are records in volumes now that no longer have a corresponding record in volumes_15min_mvt, which are the records that were aggregated given the old unacceptable_gaps model but are now excluded from aggregation. ✔️This is now solved and those `volume_15min_mvt_uid` are set as NULL 

Merging!!!!!!

**Comment by chmnata** [comment]
Ran into a dependency issue while @gabrielwol was dropping volume agg table in his schema. This is what we run to solve it. #838 created to update the table structure to include default column value. 

```
-- Change old sequence name to _outdate
ALTER SEQUENCE IF EXISTS miovision_api.volumes_15min_volume_15min_uid_seq
	RENAME TO  volumes_15min_volume_15min_uid_seq_outdated;
ALTER SEQUENCE IF EXISTS miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq
	RENAME TO  volumes_15min_mvt_volume_15min_mvt_uid_seq_outdated;
-- Set new seq schema to miovision_api	
ALTER SEQUENCE gwolofs.volumes_15min_volume_15min_uid_seq SET SCHEMA miovision_api;
ALTER SEQUENCE gwolofs.volumes_15min_mvt_volume_15min_mvt_uid_seq SET SCHEMA miovision_api;
-- Change owner of new seq
ALTER SEQUENCE miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq OWNER TO miovision_admins;
ALTER SEQUENCE miovision_api.volumes_15min_volume_15min_uid_seq OWNER TO miovision_admins;	
-- Change seq column owner 
ALTER SEQUENCE IF EXISTS miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq
	OWNED BY miovision_api.volumes_15min_mvt.volume_15min_mvt_uid;
ALTER SEQUENCE IF EXISTS miovision_api.volumes_15min_volume_15min_uid_seq
	OWNED BY miovision_api.volumes_15min.volume_15min_uid;

-- Set default value of column to use seq
ALTER TABLE miovision_api.volumes_15min_mvt 
	ALTER COLUMN volume_15min_mvt_uid 
		SET DEFAULT (nextval('miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq'));

ALTER TABLE miovision_api.volumes_15min 
	ALTER COLUMN volume_15min_uid 
		SET DEFAULT (nextval('miovision_api.volumes_15min_volume_15min_uid_seq'));

-- grant permission to bots and humans
GRANT ALL ON SEQUENCE miovision_api.volumes_15min_volume_15min_uid_seq TO bdit_bots;
GRANT SELECT ON SEQUENCE miovision_api.volumes_15min_volume_15min_uid_seq TO bdit_humans;
GRANT ALL ON SEQUENCE miovision_api.volumes_15min_volume_15min_uid_seq TO miovision_admins WITH GRANT OPTION;
GRANT ALL ON SEQUENCE miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq TO bdit_bots;
GRANT SELECT ON SEQUENCE miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq TO bdit_humans;
GRANT ALL ON SEQUENCE miovision_api.volumes_15min_mvt_volume_15min_mvt_uid_seq TO miovision_admins WITH GRANT OPTION;
```
