### PR TITLE
#1278 add separate functions to delete ARs, merge consecutive ARs

### LINKED ISSUE #1278: Clear automated anomalous_ranges during pull
When pulling Miovision data, it would be nice to automatically clear anomalous ranges for that specific range/intersection. 
This would have helped today when I reran 19 intersections that had failed to pull initially due to an API error (likely AWS related).

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:

3 new functions:
- delete auto ARs for one day
- merge consecutive/overlapping ARs
- perform delete + add + merge functions in sequence

## Issue(s) this solves:

- Closes #1278

## What, in particular, needs to reviewed:
- 

## What needs to be done by a sysadmin after this PR is merged

_E.g.: these tables need to be migrated/created in the production schema._

Test:

```sql
DROP TABLE IF EXISTS gwolofs.anomalous_range_copy_20251106;

CREATE TABLE gwolofs.anomalous_range_copy_20251106 AS SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges;

SELECT miovision_api.identify_anomalous_ranges('2025-11-01'::date);

--check results are the same:
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges
EXCEPT
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM gwolofs.anomalous_range_copy_20251106;

SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM gwolofs.anomalous_range_copy_20251106
EXCEPT
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges
```

```sql
--also test with some intersections that have outages;
SELECT * FROM miovision_api.anomalous_ranges ar WHERE
        ar.range_start = '2025-11-01'::date
        AND ar.range_end = '2025-11-01'::date + 1
        AND ar.investigation_level = 'auto_flagged';

DROP TABLE IF EXISTS gwolofs.anomalous_range_copy_20251106;

CREATE TABLE gwolofs.anomalous_range_copy_20251106 AS SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges;

SELECT miovision_api.identify_anomalous_ranges('2025-11-01'::date, '{49, 54}'::int[]);

--check results are the same:
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges
EXCEPT
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM gwolofs.anomalous_range_copy_20251106;

SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM gwolofs.anomalous_range_copy_20251106
EXCEPT
SELECT intersection_uid, classification_uid, notes, investigation_level, problem_level, range_start, range_end, leg FROM miovision_api.anomalous_ranges
```

### CODE REVIEW

File: volumes/miovision/sql/function/function-delete_anomalous_ranges.sql [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        GREATEST(delete_anomalous_ranges.ds + 1, range_start) AS range_start, range_end
+    FROM ranges_to_split
+    --new range is still valid after roll forward
+    WHERE GREATEST(delete_anomalous_ranges.ds + 1, range_start) < range_end;
+
+END;
+
+$$ LANGUAGE plpgsql;
+
+ALTER FUNCTION miovision_api.get_intersections_uids
```
Comment (Nate-Wessel) [inline volumes/miovision/sql/function/function-delete_anomalous_ranges.sql]: Should be `miovision_api.delete_anomalous_ranges` instead of `miovision_api.get_intersections_uids`? I.e. setting ownership of function just defined?
